remote_theme: pages themes/cayman@v0.2.0: 
title: Сайт візитівка бібліотеки
# Сайт візитівка бібліотеки
Кваліфікаційна робота на підтвердження ступеня фахового молодшого  бакалавра ([ВСП «ППФК НТУ «ХПІ»](http://polytechnic.poltava.ua)). Керівник  роботи – **Ковальова Наталія Володимирівна**. 
## Завдання до дипломної роботи  
розроблений продукт має являти собою інформаційний сайт бібліотеки. Основна функціональність сайту: вибір мови для локалізації сайту, загальна інформація про бібліотеку (контакти, адреса, розташування на мапі), новини бібліотеки, електронний каталог з можливістю пошуку за автором. Розроблений сайт та використані технології мають бути детально описані у пояснювальній записці.
## Використані технології 
* Java
* Spring Boot
* HTML, CSS, JavaScript
* MySQL
* Thymeleaf
* Bootstrap

